name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run tests
      run: |
        pytest tests/

    - name: Run linting
      run: |
        black . --check
        isort . --check
        flake8 .
        mypy foundry_manager/

    - name: Run version bump script
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        chmod +x ./scripts/bump_version.sh
        ./scripts/bump_version.sh patch
