name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pip install pre-commit changelog sphinx

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

    - name: Run linting
      run: |
        poetry run pre-commit run --all-files

    - name: Run tests
      run: |
        poetry run pytest

    - name: Bump version and create tag
      id: bump
      run: |
        # Get current version
        CURRENT_VERSION=$(poetry version -s)
        # Bump version
        poetry version patch
        # Stage and commit changes
        git add pyproject.toml CHANGELOG.md
        git commit -m "Bump version to $(poetry version -s)"
        # Create tag if it doesn't exist
        TAG="v$(poetry version -s)"
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG already exists. Skipping tag creation."
          echo "should_release=false" >> $GITHUB_OUTPUT
        else
          git tag $TAG
          git push origin $TAG
          echo "should_release=true" >> $GITHUB_OUTPUT
        fi
        git push origin HEAD:main

    - name: Generate changelog
      if: startsWith(github.ref, 'refs/tags/') || steps.bump.outputs.should_release == 'true'
      run: |
        poetry run changelog generate-md CHANGELOG.md

    - name: Build package
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || steps.bump.outputs.should_release == 'true')
      run: |
        poetry build

    - name: Create GitHub release
      if: startsWith(github.ref, 'refs/tags/') || steps.bump.outputs.should_release == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to PyPI
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || steps.bump.outputs.should_release == 'true')
      run: |
        poetry publish
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
